#!/bin/bash
if [ ! -f ${UNREAL_HOME}/unrealircd/conf/unrealircd.conf ]; then
        cp -Rpv /unrealircd_defaultconf/* ${UNREAL_HOME}/unrealircd/conf/
#	cp -Rpv /unrealircd_defaultconf/examples/example.conf ${UNREAL_HOME}/unrealircd/conf/unrealircd.conf
fi

cd ${UNREAL_HOME}/unrealircd/conf/ssl/

if [ ! -f server.cert.pem ]; then
  openssl req -new -out server.req.pem -keyout server.key.pem -nodes -config openssl.cnf -batch
  openssl req -x509 -days 3650 -sha256 -in server.req.pem -key server.key.pem -out server.cert.pem 
  openssl x509 -subject -dates -fingerprint -noout -in server.cert.pem 
  chmod o-rwx server.req.pem server.key.pem server.cert.pem 
  chmod g-rwx server.req.pem server.key.pem server.cert.pem
fi
if [ ! -f ${UNREAL_HOME}/unrealircd/conf/unrealircd.conf ]; then
 echo ""
 echo "******************************************************"
 echo "You NEED to copy conf/example.conf to conf/unrealircd.conf and adjust it to your needs to run unrealircd!"
 echo "be sure you mapped a volume in here e.g.:"
 echo " mkdir -p /mnt/docker/unrealircd/"
 echo " chown 1000:1000 /mnt/docker/unrealircd/"
 echo " docker run --rm -v /mnt/docker/unrealircd:/usr/local/unrealircd/conf -p 6667:6667 metabool/unrealircd4"
 echo " copy & edit /mnt/docker/unrealircd/examples/example.conf to /mnt/docker/unrealircd/unrealircd.conf"
 echo " docker run -d --rm -v /mnt/docker/unrealircd:/usr/local/unrealircd/conf -p 6667:6667 metabool/unrealircd4"
 echo ""
 echo "******************************************************"

 exit 0
fi

${UNREAL_HOME}/unrealircd/bin/unrealircd -F -f ${UNREAL_HOME}/unrealircd/conf/unrealircd.conf
PID=$!
trap "kill -SIGTERM $PID" SIGINT SIGTERM 
wait
echo "Exiting..."
exit 0
